version: '2'

services:
  db:
    image: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  django:
    image: louisbertin/django:v0.0.5
    ports:
      - "80:80"
    depends_on:
      - db
      - adminer