version: '2'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
      - adminer

volumes:
  postgres_data: