# Generated by Django 2.2.2 on 2019-06-07 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
